### ISSUE TITLE
How would you specify options and an action ?

### ISSUE THREAD

**Issue by conradkleinespel** [absentik/DataSaver#4]
Hello @absentik,

Thanks for your work on this library. I appreciate it. It is very useful ! :+1: 

I am wondering if it is currently possible to specify both options to DataSaver, such as `keyUrlAttrs` and an action such as `load`. It seems like both the options and the actions use the same function argument, as in `DataSaver({ ... })` and `DataSaver('load')` with no way of using both.

Is this correct? If so, I am glad to make a patch if needed. We could allow the options to be passed second if an action is specified. This would keep backwards compatibility intact.

Best regards,
Conrad

**Comment by absentik** [comment]
Hello @conradkleinespel. Thank you. 
You are right. We can't specify an options object with an action together. I don't think that such a possibility is necessary. Jquery allows use chaining: `$(element).DataSaver({...}).DataSaver('action')` (I didn't test, but it should work). If I'm wrong and you feel it necessary, describe the example in which it would be required.

**Comment by conradkleinespel** [comment]
Hi @absentik,

Thanks for replying so quickly. That's awesome!

The example I had was something like this:

``` javascript
document.getElementById('form-submit-button').addEventListener('click', function() {
    $('input, textarea, select, option').DataSaver('save', {
        keyUrlAttrs: ['host'],
        keyExtra: function() {
            return 'advanced-calc';
        }
    });
    document.location = 'someOtherForm';
});
```

In this example, my form values are saved just before redirecting to a similar but slightly different form, which calls `DataSaver('load', { options... })`.

Feel free to let me know if you have any more questions about my use case.

By default, `DataSaver` calls the `start` action, which is not what I want, because then form values are saved no matter if I need to save them or not.

Best regards,
Conrad

**Comment by absentik** [comment]
Try this way: http://jsfiddle.net/absentik/qykscepw/

**Save data on some page:**

``` javascript
$(document).ready(function() {
    //Init DataSaver on page loaded
    $('input, textarea, select, option').DataSaver({
        keyUrlAttrs: ['host'],
        keyExtra: function() {
            return 'advanced-calc';
        },
        timeout: 0, //Don't save data on timeout
        events: ''  //Don't use events for save data
    });
});

document.getElementById('form-submit-button').addEventListener('click', function() {
    //Save data on #form-submit-button click
    $('input, textarea, select, option').DataSaver('save'); 
    //Redirect to /someOtherForm
    document.location = 'someOtherForm';
});
```

**Load data on page `/someOtherForm`:** 

``` javascript
$(document).ready(function() {
    //Init DataSaver on page loaded
    $('input, textarea, select, option').DataSaver({
        keyUrlAttrs: ['host'],
        keyExtra: function() {
            return 'advanced-calc';
        },
        timeout: 0, //Don't save data on timeout
        events: ''  //Don't use events for save data
    });
});
```

**Comment by conradkleinespel** [comment]
Alright, thanks a lot @absentik ! This helps :+1:
